import { z } from 'zod';

/**
 * Zod schema for a trip
 * Matches the `public.trips` table in Supabase
 * 
 * Note: user_id removed - trips use many-to-many relationship via trip_members table
 */
export const TripSchema = z.object({
  id: z.string().uuid('Invalid trip ID format'),
  title: z
    .string()
    .min(1, 'Title is required')
    .max(200, 'Title must be less than 200 characters')
    .nullable()
    .optional(),
  destination: z
    .string()
    .min(1, 'Destination is required')
    .max(200, 'Destination must be less than 200 characters')
    .nullable()
    .optional(),
  start_date: z
    .string()
    .datetime({ message: 'Invalid start date format' })
    .nullable()
    .optional(),
  end_date: z
    .string()
    .datetime({ message: 'Invalid end date format' })
    .nullable()
    .optional(),
  image_url: z.union([z.string().url('Invalid image URL'), z.null(), z.undefined()]).optional(),
  color: z.union([z.string(), z.null(), z.undefined()]).optional(),
  description: z
    .string()
    .max(2000, 'Description must be less than 2000 characters')
    .nullable()
    .optional(),
  created_at: z.string().datetime({ message: 'Invalid creation date format' }),
})
.refine(
  (data) => {
    // Validate that end_date is after start_date if both are provided
    if (data.start_date && data.end_date) {
      return new Date(data.end_date) >= new Date(data.start_date);
    }
    return true;
  },
  {
    message: 'End date must be after or equal to start date',
    path: ['end_date'],
  }
);

/**
 * Zod schema for trip member (bridge table)
 * Matches the `public.trip_members` table in Supabase
 */
export const TripMemberSchema = z.object({
  trip_id: z.string().uuid('Invalid trip ID format'),
  user_id: z.string().uuid('Invalid user ID format'),
  joined_at: z.string().datetime({ message: 'Invalid join date format' }),
});

/**
 * Schema for creating a new trip
 * ID and created_at are auto-generated by the database
 */
export const CreateTripSchema = TripSchema.omit({
  id: true,
  created_at: true,
});

/**
 * Schema for updating an existing trip
 * All fields except id and created_at are optional
 */
export const UpdateTripSchema = TripSchema.omit({
  created_at: true,
}).partial().required({ id: true });

/**
 * Schema for trip update request (without ID)
 * Used in API endpoints where ID comes from route params
 */
export const TripUpdateDataSchema = TripSchema.omit({
  id: true,
  created_at: true,
}).partial();

/**
 * Schema for adding a member to a trip
 */
export const AddTripMemberSchema = z.object({
  trip_id: z.string().uuid('Invalid trip ID format'),
  user_id: z.string().uuid('Invalid user ID format'),
});

/**
 * Schema for removing a member from a trip
 */
export const RemoveTripMemberSchema = z.object({
  trip_id: z.string().uuid('Invalid trip ID format'),
  user_id: z.string().uuid('Invalid user ID format'),
});

/**
 * Schema for trip creation request
 * Used in API endpoints - user will be auto-added as member after creation
 */
export const TripCreateDataSchema = TripSchema.omit({
  id: true,
  created_at: true,
})
.partial()
.refine(
  (data) => {
    // Validate that end_date is after start_date if both are provided
    if (data.start_date && data.end_date) {
      return new Date(data.end_date) >= new Date(data.start_date);
    }
    return true;
  },
  {
    message: 'End date must be after or equal to start date',
    path: ['end_date'],
  }
);

/**
 * TypeScript types inferred from Zod schemas
 */
export type Trip = z.infer<typeof TripSchema>;
export type TripMember = z.infer<typeof TripMemberSchema>;
export type CreateTrip = z.infer<typeof CreateTripSchema>;
export type UpdateTrip = z.infer<typeof UpdateTripSchema>;
export type TripUpdateData = z.infer<typeof TripUpdateDataSchema>;
export type TripCreateData = z.infer<typeof TripCreateDataSchema>;
export type AddTripMember = z.infer<typeof AddTripMemberSchema>;
export type RemoveTripMember = z.infer<typeof RemoveTripMemberSchema>;


